version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    environment:
        BUNDLER_VERSION: 2.0.1

#    steps:
#      - checkout
#      - run: cd android
#      - restore_cache:
#          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
#
#      #- run: bundle check || bundle install --path android/vendor/bundle
#      - save_cache:
#          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
#          paths:
#            - android/vendor/bundle
#      - run:
#          name: fastlane
#          command: |
#            cd android
#            bundle exec fastlane supply
#      - store_artifacts:
#          path: android/output
#      - store_test_results:
#          path: android/output/scan

    steps:
      - checkout
#      - run:
#          cd android
      #- restore_cache:
      #    key: 1-gems-{{ checksum "android/Gemfile.lock" }}
#      - run:
#          name: Init fastlane supply
#          command: |
#            cd android
#            bundle exec fastlane supply init
      - run:
          name: Force Bundler Version
          command: |
            cd android
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler
            sudo bundle install
      - run:
          name: Do Anything Bundler Related
          command: |
            sudo bundler -v
      - run:
          name: Deploy the app to the internal track
          command: |
            cd android
            bundle exec fastlane supply
      - save_cache:
          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
          paths:
              - android/vendor/bundle