version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    environment:
        BUNDLER_VERSION: 2.0.1
    #steps:
    #    - checkout
    #    - run: flutter doctor
    #    - run: flutter test 
    #    - run: flutter -v build apk
    
#    steps:
#      - checkout
#      - run: cd android
#      - restore_cache:
#          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
#
#      #- run: bundle check || bundle install --path android/vendor/bundle
#      - save_cache:
#          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
#          paths:
#            - android/vendor/bundle
#      - run:
#          name: fastlane
#          command: |
#            cd android
#            bundle exec fastlane supply
#      - store_artifacts:
#          path: android/output
#      - store_test_results:
#          path: android/output/scan

    steps:
      - checkout
      - run:
          cd android
      #- restore_cache:
      #    key: 1-gems-{{ checksum "android/Gemfile.lock" }}
#      - run:
#          name: Init fastlane supply
#          command: |
#            cd android
#            bundle exec fastlane supply init
      - run:
          name: Deploy the app to the internal track
          command: |
            cd C:\Users\
            bundle -v
            gem install bundler -v 2.0.1
            bundle exec fastlane supply
      - save_cache:
          key: 1-gems-{{ checksum "android/Gemfile.lock" }}
          paths:
              - android/vendor/bundle