version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    #steps:
    # - checkout
    # - run: flutter doctor
    #  - run: flutter test 
    #  - run: flutter -v build apk
    
    steps:
      #- checkout
      #- restore_cache:
      #    key: 1-gems-{{ checksum "Gemfile.lock" }}
      #- run: cd android
      #- run: bundle check || bundle install --path vendor/bundle
      #- save_cache:
      #    key: 1-gems-{{ checksum "Gemfile.lock" }}
      #    paths:
      #      - vendor/bundle
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
